##
## EPITECH PROJECT, 2024
## Raytracer
## File description:
## Makefile
##

all:
	make -C ./Sphere/
	make -C ./Plane/
	make -C ./Cone/

clean:
	make clean -C ./Sphere/
	make clean -C ./Plane/
	make -C ./Cone/

fclean: clean
	make fclean -C ./Sphere/
	make fclean -C ./Plane/
	make -C ./Cone/

re:	fclean all
