##
## EPITECH PROJECT, 2024
## Raytracer
## File description:
## Makefile
##

all:
	make -C ./Ambient/
	make -C ./Point/
	make -C ./Directional/

clean:
	make clean -C ./Ambient/
	make clean -C ./Point/
	make clean -C ./Directional/

fclean: clean
	make fclean -C ./Ambient/
	make fclean -C ./Point/
	make fclean -C ./Directional/

re:	fclean all
